const products = [
  {
    id: 1,
    name: "Vanilla Protein Powder",
    ref: "2FU8C88TR78",
    price: 24.99,
    rating: 3,
    desc: "A high-quality protein powder perfect for smoothies and baking.",
    image: "http://dummyimage.com/202x100.png/cc0000/ffffff",
  },
  {
    id: 2,
    name: "Classic Caesar Dressing",
    ref: "9X90E28FA58",
    price: 3.49,
    rating: 1,
    desc: "Rich and creamy Caesar dressing for salads and wraps.",
    image: "http://dummyimage.com/187x100.png/cc0000/ffffff",
  },
  {
    id: 3,
    name: "Classic White T-Shirt",
    ref: "1M15R40PE76",
    price: 19.99,
    rating: 4,
    desc: "A timeless wardrobe staple crafted from soft cotton with a perfect fit.",
    image: "http://dummyimage.com/134x100.png/ff4444/ffffff",
  },
  {
    id: 4,
    name: "High-Speed Hand Blender",
    ref: "2JQ3U87NY92",
    price: 39.99,
    rating: 2,
    desc: "Powerful hand blender for soups and smoothies.",
    image: "http://dummyimage.com/118x100.png/cc0000/ffffff",
  },
  {
    id: 5,
    name: "Casual Sneakers",
    ref: "4GC9XH8RM20",
    price: 39.99,
    rating: 2,
    desc: "Versatile canvas sneakers suitable for everyday wear with a comfortable fit.",
    image: "http://dummyimage.com/108x100.png/5fa2dd/ffffff",
  },
  {
    id: 6,
    name: "Chocolate Raspberry Tart",
    ref: "3WX5KD0JN02",
    price: 9.99,
    rating: 5,
    desc: "Rich tart filled with chocolate and raspberry, a gourmet dessert.",
    image: "http://dummyimage.com/111x100.png/cc0000/ffffff",
  },
  {
    id: 7,
    name: "Vegetable Lasagna",
    ref: "1MA1DT9DR45",
    price: 6.99,
    rating: 4,
    desc: "Layers of pasta, veggies, and cheese baked to perfection.",
    image: "http://dummyimage.com/136x100.png/ff4444/ffffff",
  },
  {
    id: 8,
    name: "Organic Black Rice",
    ref: "7HW5PW3NG67",
    price: 3.59,
    rating: 2,
    desc: "Nutty and chewy black rice, high in antioxidants.",
    image: "http://dummyimage.com/101x100.png/5fa2dd/ffffff",
  },
  {
    id: 9,
    name: "Fleece Hoodie",
    ref: "2RH9R51TH25",
    price: 39.99,
    rating: 3,
    desc: "Ultra-soft fleece hoodie for warmth and comfort during chilly days.",
    image: "http://dummyimage.com/231x100.png/ff4444/ffffff",
  },
  {
    id: 10,
    name: "Bluetooth Headphones",
    ref: "3UW1E67CM07",
    price: 79.99,
    rating: 2,
    desc: "Noise-cancelling Bluetooth headphones for immersive sound.",
    image: "http://dummyimage.com/205x100.png/5fa2dd/ffffff",
  },
  {
    id: 11,
    name: "Almond Butter Crunch Bar",
    ref: "3EF8G25MQ02",
    price: 1.99,
    rating: 2,
    desc: "Nutritious snack bar made with almond butter and protein.",
    image: "http://dummyimage.com/194x100.png/dddddd/000000",
  },
  {
    id: 12,
    name: "High-Low Hem Tee",
    ref: "1QW1W29QP26",
    price: 22.99,
    rating: 5,
    desc: "Trendy high-low tee with a relaxed fit, ideal for weekends.",
    image: "http://dummyimage.com/147x100.png/cc0000/ffffff",
  },
  {
    id: 13,
    name: "Sliced Bell Peppers",
    ref: "6TW9VX5MV51",
    price: 3.99,
    rating: 4,
    desc: "Fresh sliced bell peppers for salads or stir-fries.",
    image: "http://dummyimage.com/143x100.png/dddddd/000000",
  },
  {
    id: 14,
    name: "Portable Air Compressor",
    ref: "1A02T32DF08",
    price: 44.99,
    rating: 5,
    desc: "Compact air compressor for inflating tires and sports equipment.",
    image: "http://dummyimage.com/130x100.png/ff4444/ffffff",
  },
  {
    id: 15,
    name: "Tortilla Chips",
    ref: "5J48TN4MJ35",
    price: 2.99,
    rating: 2,
    desc: "Crispy tortilla chips, perfect for dipping.",
    image: "http://dummyimage.com/188x100.png/ff4444/ffffff",
  },
  {
    id: 16,
    name: "Almond Joy Protein Bars",
    ref: "1YC0VK3TP10",
    price: 1.99,
    rating: 2,
    desc: "Chocolate coconut protein bars inspired by the classic candy bar.",
    image: "http://dummyimage.com/107x100.png/cc0000/ffffff",
  },
  {
    id: 17,
    name: "LED Christmas Lights",
    ref: "7C17N61NN52",
    price: 29.99,
    rating: 2,
    desc: "Eco-friendly LED lights for festive decorations.",
    image: "http://dummyimage.com/211x100.png/cc0000/ffffff",
  },
  {
    id: 18,
    name: "Mini Meatballs",
    ref: "9G58HU0NR38",
    price: 5.99,
    rating: 2,
    desc: "Frozen mini meatballs that are great as a snack or in pasta dishes.",
    image: "http://dummyimage.com/114x100.png/dddddd/000000",
  },
  {
    id: 19,
    name: "Radish Chips",
    ref: "5CV0AW2UG82",
    price: 2.89,
    rating: 3,
    desc: "Crispy baked radish chips, a healthy snack alternative.",
    image: "http://dummyimage.com/183x100.png/dddddd/000000",
  },
  {
    id: 20,
    name: "Car Seat Organizer",
    ref: "3HA1NV4DH61",
    price: 14.99,
    rating: 1,
    desc: "Storage solutions for keeping your car tidy and organized.",
    image: "http://dummyimage.com/107x100.png/cc0000/ffffff",
  },
  {
    id: 21,
    name: "Key Finder",
    ref: "4C37YX3XF70",
    price: 19.99,
    rating: 4,
    desc: "Bluetooth-enabled key tracker to find lost items easily.",
    image: "http://dummyimage.com/183x100.png/dddddd/000000",
  },
  {
    id: 22,
    name: "Pet Travel Carrier",
    ref: "4VT2G95CD00",
    price: 39.99,
    rating: 2,
    desc: "Comfortable carrier for small pets during travel.",
    image: "http://dummyimage.com/167x100.png/cc0000/ffffff",
  },
  {
    id: 23,
    name: "Kids' Educational Tablet",
    ref: "4CN1UW0CP68",
    price: 129.99,
    rating: 1,
    desc: "Learning tablet with kid-friendly educational apps.",
    image: "http://dummyimage.com/118x100.png/ff4444/ffffff",
  },
  {
    id: 24,
    name: "Board Game Storage",
    ref: "9GC0FA7AY15",
    price: 19.99,
    rating: 4,
    desc: "Organize your board games with this storage bin.",
    image: "http://dummyimage.com/133x100.png/5fa2dd/ffffff",
  },
  {
    id: 25,
    name: "Mesh Sports Leggings",
    ref: "7VY7GM0TG05",
    price: 39.99,
    rating: 1,
    desc: "Breathable mesh sports leggings for ultimate comfort.",
    image: "http://dummyimage.com/129x100.png/dddddd/000000",
  },
  {
    id: 26,
    name: "Leather Biker Jacket",
    ref: "8VW5E34KR19",
    price: 129.99,
    rating: 3,
    desc: "Stylish black leather jacket featuring a zip-up front and multiple pockets.",
    image: "http://dummyimage.com/119x100.png/ff4444/ffffff",
  },
  {
    id: 27,
    name: "Portable Pet Water Bottle",
    ref: "6VU9TR4FD37",
    price: 18.99,
    rating: 2,
    desc: "Travel-friendly water bottle for pets on the go.",
    image: "http://dummyimage.com/231x100.png/ff4444/ffffff",
  },
  {
    id: 28,
    name: "Pumpkin Spice Pancake Mix",
    ref: "3VV1TJ6KR94",
    price: 3.49,
    rating: 1,
    desc: "Pancake mix infused with seasonal pumpkin spice flavor.",
    image: "http://dummyimage.com/224x100.png/5fa2dd/ffffff",
  },
  {
    id: 29,
    name: "Lentil Pasta",
    ref: "8E91WG4UG56",
    price: 4.99,
    rating: 5,
    desc: "Gluten-free pasta made from lentils, high in protein.",
    image: "http://dummyimage.com/161x100.png/5fa2dd/ffffff",
  },
  {
    id: 30,
    name: "Spicy Kimchi",
    ref: "4Q80PF9UJ89",
    price: 4.79,
    rating: 5,
    desc: "Traditional Korean fermented vegetables, packed with flavor.",
    image: "http://dummyimage.com/202x100.png/dddddd/000000",
  },
  {
    id: 31,
    name: "Wireless Mouse",
    ref: "6DV8NH9GQ18",
    price: 25.99,
    rating: 3,
    desc: "Ergonomic wireless mouse with adjustable DPI.",
    image: "http://dummyimage.com/233x100.png/dddddd/000000",
  },
  {
    id: 32,
    name: "Homestyle Beef Stew",
    ref: "8R12UQ3TA94",
    price: 7.99,
    rating: 5,
    desc: "Hearty beef stew with vegetables, ready to heat and serve.",
    image: "http://dummyimage.com/162x100.png/5fa2dd/ffffff",
  },
  {
    id: 33,
    name: "LED Canopy Lights",
    ref: "9C51M80CD73",
    price: 29.99,
    rating: 1,
    desc: "Energy-efficient lights to illuminate outdoor areas.",
    image: "http://dummyimage.com/156x100.png/ff4444/ffffff",
  },
  {
    id: 34,
    name: "Strawberry Fruit Spread",
    ref: "6F95TR6FU34",
    price: 3.59,
    rating: 2,
    desc: "Natural fruit spread bursting with real strawberry flavor.",
    image: "http://dummyimage.com/152x100.png/cc0000/ffffff",
  },
  {
    id: 35,
    name: "French Onion Dip",
    ref: "8XR8D58JQ80",
    price: 2.99,
    rating: 2,
    desc: "Creamy dip made with real onions and spices, great for chips and veggies.",
    image: "http://dummyimage.com/226x100.png/ff4444/ffffff",
  },
  {
    id: 36,
    name: "Electric Bike",
    ref: "6P64VY5MT09",
    price: 899.99,
    rating: 1,
    desc: "Eco-friendly electric bike with a 30-mile range.",
    image: "http://dummyimage.com/172x100.png/dddddd/000000",
  },
  {
    id: 37,
    name: "Thai Peanut Dressing",
    ref: "1TV0GG2XH24",
    price: 3.29,
    rating: 4,
    desc: "A creamy and tangy dressing perfect for salads or as a dipping sauce.",
    image: "http://dummyimage.com/161x100.png/dddddd/000000",
  },
  {
    id: 38,
    name: "Vegetable Stir-Fry Kit",
    ref: "6PU7W56CM32",
    price: 6.99,
    rating: 5,
    desc: "A mix of fresh vegetables with a savory stir-fry sauce, ready to cook.",
    image: "http://dummyimage.com/233x100.png/ff4444/ffffff",
  },
  {
    id: 39,
    name: "Beef Jerky",
    ref: "3KX2E69PE28",
    price: 5.99,
    rating: 3,
    desc: "Savory, protein-rich beef jerky for on-the-go snacking.",
    image: "http://dummyimage.com/175x100.png/ff4444/ffffff",
  },
  {
    id: 40,
    name: "Spicy Kimchi",
    ref: "7QM9JE4EK66",
    price: 4.79,
    rating: 5,
    desc: "Traditional Korean fermented vegetables, packed with flavor.",
    image: "http://dummyimage.com/160x100.png/cc0000/ffffff",
  },
  {
    id: 41,
    name: "Graphic Hoodie",
    ref: "7G47T29XE98",
    price: 49.99,
    rating: 2,
    desc: "Bold graphic hoodie featuring a comfortable fit and soft fabric.",
    image: "http://dummyimage.com/212x100.png/ff4444/ffffff",
  },
  {
    id: 42,
    name: "Beef Enchilada Casserole",
    ref: "2U27YP8UN35",
    price: 8.99,
    rating: 2,
    desc: "Hearty casserole with beef and enchilada sauce.",
    image: "http://dummyimage.com/142x100.png/dddddd/000000",
  },
  {
    id: 43,
    name: "Peanut Butter Banana Smoothie Mix",
    ref: "9D04U39PY02",
    price: 4.49,
    rating: 5,
    desc: "Smoothie mix combining peanut butter and banana, great for a quick breakfast.",
    image: "http://dummyimage.com/175x100.png/cc0000/ffffff",
  },
  {
    id: 44,
    name: "Mini Food Processor",
    ref: "5VC0XM7RX98",
    price: 39.99,
    rating: 4,
    desc: "Compact food processor for quick meal prep.",
    image: "http://dummyimage.com/104x100.png/5fa2dd/ffffff",
  },
  {
    id: 45,
    name: "Smoked Paprika Chicken Thighs",
    ref: "4VA3UT0FF94",
    price: 6.99,
    rating: 3,
    desc: "Marinated chicken thighs with smoked paprika for a smoky flavor.",
    image: "http://dummyimage.com/158x100.png/dddddd/000000",
  },
  {
    id: 46,
    name: "Dog Training Collar",
    ref: "6RH5VE2TR26",
    price: 39.99,
    rating: 2,
    desc: "Rechargeable training collar for effective behavior training.",
    image: "http://dummyimage.com/143x100.png/ff4444/ffffff",
  },
  {
    id: 47,
    name: "Teriyaki Chicken Stir-Fry",
    ref: "3R34DE1UY38",
    price: 6.99,
    rating: 4,
    desc: "Frozen stir-fry mix with chicken, veggies, and teriyaki sauce.",
    image: "http://dummyimage.com/236x100.png/cc0000/ffffff",
  },
  {
    id: 48,
    name: "Wall Decals for Kids",
    ref: "2Q80N74XY77",
    price: 24.99,
    rating: 2,
    desc: "Fun and colorful wall decals for children's rooms.",
    image: "http://dummyimage.com/124x100.png/5fa2dd/ffffff",
  },
  {
    id: 49,
    name: "Comfortable Bed Pillow",
    ref: "6JN6MP5TR34",
    price: 24.99,
    rating: 1,
    desc: "Supportive pillow designed for a good night's sleep.",
    image: "http://dummyimage.com/212x100.png/dddddd/000000",
  },
  {
    id: 50,
    name: "Travel Organizer",
    ref: "6V12T27VH12",
    price: 22.99,
    rating: 4,
    desc: "Compact travel organizer for accessories and toiletries.",
    image: "http://dummyimage.com/184x100.png/cc0000/ffffff",
  },
  {
    id: 51,
    name: "Sweet Chili Dipping Sauce",
    ref: "2F94VW4PF67",
    price: 2.99,
    rating: 3,
    desc: "A sweet and spicy sauce ideal for spring rolls or chicken nuggets.",
    image: "http://dummyimage.com/227x100.png/dddddd/000000",
  },
  {
    id: 52,
    name: "Craft Beer Mustard",
    ref: "1G99AT7KA88",
    price: 3.99,
    rating: 1,
    desc: "Stone-ground mustard infused with craft beer for a gourmet touch.",
    image: "http://dummyimage.com/247x100.png/5fa2dd/ffffff",
  },
  {
    id: 53,
    name: "Inflatable Paddle Board",
    ref: "2FK7VU0FQ16",
    price: 349.99,
    rating: 4,
    desc: "Lightweight and portable paddle board for water sports.",
    image: "http://dummyimage.com/246x100.png/dddddd/000000",
  },
  {
    id: 54,
    name: "Green Tea Matcha Powder",
    ref: "4E56XG3AX89",
    price: 15.99,
    rating: 2,
    desc: "High-quality matcha powder for smoothies and baking.",
    image: "http://dummyimage.com/230x100.png/ff4444/ffffff",
  },
  {
    id: 55,
    name: "Crispy Rice Treats",
    ref: "3VC2VF9UM18",
    price: 3.5,
    rating: 2,
    desc: "Classic marshmallow treats made with crispy rice.",
    image: "http://dummyimage.com/193x100.png/5fa2dd/ffffff",
  },
  {
    id: 56,
    name: "Portable Grill Cover",
    ref: "6W60A63NK21",
    price: 24.99,
    rating: 3,
    desc: "Durable cover to protect your grill from the elements.",
    image: "http://dummyimage.com/203x100.png/dddddd/000000",
  },
  {
    id: 57,
    name: "LED Disco Ball Light",
    ref: "4FM4Y14RA09",
    price: 19.99,
    rating: 3,
    desc: "Fun light that creates a disco atmosphere for parties.",
    image: "http://dummyimage.com/240x100.png/ff4444/ffffff",
  },
  {
    id: 58,
    name: "Aeropress Coffee Maker",
    ref: "6A15K21AX63",
    price: 29.99,
    rating: 4,
    desc: "Portable coffee maker for rich brews on the go.",
    image: "http://dummyimage.com/114x100.png/cc0000/ffffff",
  },
  {
    id: 59,
    name: "Spinach Feta Wraps",
    ref: "1T31TX1RQ05",
    price: 4.29,
    rating: 2,
    desc: "Whole wheat wraps filled with spinach, feta, and herbs.",
    image: "http://dummyimage.com/245x100.png/5fa2dd/ffffff",
  },
  {
    id: 60,
    name: "Vacuum Sealer Machine",
    ref: "1W80E09MM39",
    price: 89.99,
    rating: 4,
    desc: "Seal food and maintain freshness longer.",
    image: "http://dummyimage.com/189x100.png/dddddd/000000",
  },
  {
    id: 61,
    name: "Caramel Apple Chips",
    ref: "6YD1R72MN08",
    price: 3.49,
    rating: 2,
    desc: "Crispy apple chips drizzled with caramel for a sweet treat.",
    image: "http://dummyimage.com/229x100.png/ff4444/ffffff",
  },
  {
    id: 62,
    name: "Wooden Toy Train Set",
    ref: "9RC6WM8ET97",
    price: 29.99,
    rating: 3,
    desc: "Classic wooden train set for imaginative play.",
    image: "http://dummyimage.com/246x100.png/dddddd/000000",
  },
  {
    id: 63,
    name: "Miso Dressing",
    ref: "3WX1TF2MQ02",
    price: 3.49,
    rating: 2,
    desc: "Flavorful dressing made with miso paste",
    image: "http://dummyimage.com/151x100.png/cc0000/ffffff",
  },
  {
    id: 64,
    name: "Classic Chicken Noodle Soup",
    ref: "4JJ7D57PD63",
    price: 3.49,
    rating: 2,
    desc: "A comforting soup filled with chicken and noodles in broth.",
    image: "http://dummyimage.com/148x100.png/dddddd/000000",
  },
  {
    id: 65,
    name: "Digital Alarm Clock",
    ref: "9GV7RU6YY36",
    price: 19.99,
    rating: 2,
    desc: "Snooze function and LED display for easy reading.",
    image: "http://dummyimage.com/167x100.png/dddddd/000000",
  },
  {
    id: 66,
    name: "Kale Chips",
    ref: "8PU1GD8YW72",
    price: 3.99,
    rating: 2,
    desc: "Healthy, crunchy kale chips, a nutritious snack.",
    image: "http://dummyimage.com/181x100.png/5fa2dd/ffffff",
  },
  {
    id: 67,
    name: "Chocolate Fudge Ice Cream",
    ref: "6K03XQ7AU93",
    price: 5.99,
    rating: 5,
    desc: "Rich and creamy chocolate fudge ice cream for dessert.",
    image: "http://dummyimage.com/238x100.png/ff4444/ffffff",
  },
  {
    id: 68,
    name: "Roasted Garlic Mashed Potatoes",
    ref: "6R09UC6WF28",
    price: 3.99,
    rating: 2,
    desc: "Creamy mashed potatoes infused with roasted garlic flavor.",
    image: "http://dummyimage.com/132x100.png/ff4444/ffffff",
  },
  {
    id: 69,
    name: "Mango Sticky Rice Dessert",
    ref: "4F22GN4UA25",
    price: 4.5,
    rating: 1,
    desc: "Sweetened sticky rice served with fresh mango and coconut sauce.",
    image: "http://dummyimage.com/196x100.png/5fa2dd/ffffff",
  },
  {
    id: 70,
    name: "Phone Screen Protector",
    ref: "3UY2GT7XW73",
    price: 12.99,
    rating: 2,
    desc: "Tempered glass screen protector for smartphones.",
    image: "http://dummyimage.com/140x100.png/cc0000/ffffff",
  },
  {
    id: 71,
    name: "Wireless Smart Plug",
    ref: "1XA4R33PK13",
    price: 19.99,
    rating: 4,
    desc: "Control home appliances remotely using your smartphone app.",
    image: "http://dummyimage.com/200x100.png/cc0000/ffffff",
  },
  {
    id: 72,
    name: "Creamy Ranch Dressing",
    ref: "7VG3EU3AG76",
    price: 2.49,
    rating: 3,
    desc: "Classic ranch dressing for salads and dipping.",
    image: "http://dummyimage.com/162x100.png/cc0000/ffffff",
  },
  {
    id: 73,
    name: "Sesame Garlic Stir-Fry Sauce",
    ref: "8A67JG9GC89",
    price: 2.79,
    rating: 3,
    desc: "A flavorful sauce for stir-frying vegetables and meats.",
    image: "http://dummyimage.com/170x100.png/cc0000/ffffff",
  },
  {
    id: 74,
    name: "Eco-Friendly Notepad",
    ref: "2M88Y48DP53",
    price: 8.99,
    rating: 2,
    desc: "Notepad made from recycled paper for sustainable note-taking.",
    image: "http://dummyimage.com/147x100.png/cc0000/ffffff",
  },
  {
    id: 75,
    name: "Halloween Decoration Set",
    ref: "8EF0C35YN74",
    price: 29.99,
    rating: 3,
    desc: "Fun decorations for Halloween to set a spooky atmosphere.",
    image: "http://dummyimage.com/226x100.png/cc0000/ffffff",
  },
  {
    id: 76,
    name: "Kids Tablet",
    ref: "6K79D33QM79",
    price: 129.99,
    rating: 2,
    desc: "Durable tablet designed for kids with parental controls.",
    image: "http://dummyimage.com/101x100.png/5fa2dd/ffffff",
  },
  {
    id: 77,
    name: "Pizza Stone",
    ref: "4JP1VK9JP84",
    price: 29.99,
    rating: 2,
    desc: "Ceramic pizza stone for homemade pizzas.",
    image: "http://dummyimage.com/100x100.png/dddddd/000000",
  },
  {
    id: 78,
    name: "Roasted Red Pepper Sauce",
    ref: "9WG2CE7GE58",
    price: 3.29,
    rating: 2,
    desc: "Savory sauce perfect for pasta or dipping.",
    image: "http://dummyimage.com/207x100.png/5fa2dd/ffffff",
  },
  {
    id: 79,
    name: "Honey mustard chicken tenders",
    ref: "9QV0JW2AW38",
    price: 7.99,
    rating: 4,
    desc: "Golden crispy chicken tenders coated with honey mustard flavor.",
    image: "http://dummyimage.com/190x100.png/dddddd/000000",
  },
  {
    id: 80,
    name: "Sun-Dried Tomato Pesto",
    ref: "4VJ7TK2MX28",
    price: 4.49,
    rating: 2,
    desc: "A rich pesto made with sun-dried tomatoes and pine nuts.",
    image: "http://dummyimage.com/145x100.png/cc0000/ffffff",
  },
  {
    id: 81,
    name: "Non-Stick Grill Pan",
    ref: "8HC8QE2MW37",
    price: 39.99,
    rating: 1,
    desc: "Heavy-duty grill pan for indoor grilling.",
    image: "http://dummyimage.com/165x100.png/ff4444/ffffff",
  },
  {
    id: 82,
    name: "Green Smoothie Mix",
    ref: "8C04AV0CT44",
    price: 5.99,
    rating: 4,
    desc: "A convenient powder mix combining greens and fruits for smoothies.",
    image: "http://dummyimage.com/142x100.png/dddddd/000000",
  },
  {
    id: 83,
    name: "Sliced Bell Peppers",
    ref: "2X55XX6JA52",
    price: 3.99,
    rating: 5,
    desc: "Fresh sliced bell peppers for salads or stir-fries.",
    image: "http://dummyimage.com/207x100.png/dddddd/000000",
  },
  {
    id: 84,
    name: "Portable UV Sterilizer",
    ref: "3E77G06AM77",
    price: 19.99,
    rating: 1,
    desc: "Compact sterilizer for disinfecting small items.",
    image: "http://dummyimage.com/229x100.png/dddddd/000000",
  },
  {
    id: 85,
    name: "Vegan Tacos",
    ref: "9Q82V21PV08",
    price: 7.49,
    rating: 2,
    desc: "Frozen vegan tacos filled with plant-based protein and spices.",
    image: "http://dummyimage.com/136x100.png/dddddd/000000",
  },
  {
    id: 86,
    name: "Mesh Sports Leggings",
    ref: "1D28T30RP07",
    price: 39.99,
    rating: 4,
    desc: "Breathable mesh sports leggings for ultimate comfort.",
    image: "http://dummyimage.com/229x100.png/dddddd/000000",
  },
  {
    id: 87,
    name: "Peach Mango Smoothie Mix",
    ref: "4NW2XE3AY22",
    price: 5.99,
    rating: 2,
    desc: "A blend of peach and mango for a tropical smoothie.",
    image: "http://dummyimage.com/144x100.png/ff4444/ffffff",
  },
  {
    id: 88,
    name: "Elegant Maxi Skirt",
    ref: "5AT9ER1UP54",
    price: 44.99,
    rating: 5,
    desc: "Float through the day in this beautiful floor-length skirt.",
    image: "http://dummyimage.com/180x100.png/ff4444/ffffff",
  },
  {
    id: 89,
    name: "Children's Musical Instrument Set",
    ref: "9F88V95CK97",
    price: 39.99,
    rating: 2,
    desc: "Fun instruments to introduce kids to music.",
    image: "http://dummyimage.com/182x100.png/5fa2dd/ffffff",
  },
  {
    id: 90,
    name: "Travel Pillow with Memory Foam",
    ref: "7U35UW7YV52",
    price: 29.99,
    rating: 3,
    desc: "Ergonomically designed neck pillow for comfortable travel.",
    image: "http://dummyimage.com/204x100.png/ff4444/ffffff",
  },
  {
    id: 91,
    name: "Ramen Noodle Soup Cups",
    ref: "3KX9CD4GG84",
    price: 1.29,
    rating: 2,
    desc: "Instant ramen cups with flavor-packed broth.",
    image: "http://dummyimage.com/213x100.png/5fa2dd/ffffff",
  },
  {
    id: 92,
    name: "Car Vacuum",
    ref: "2HF5C25EP08",
    price: 49.99,
    rating: 3,
    desc: "Portable car vacuum cleaner with strong suction.",
    image: "http://dummyimage.com/131x100.png/ff4444/ffffff",
  },
  {
    id: 93,
    name: "Magnetic Curtain Tiebacks",
    ref: "1CT9YH7WW04",
    price: 12.99,
    rating: 3,
    desc: "Easy-to-use tiebacks for curtains or drapes.",
    image: "http://dummyimage.com/150x100.png/dddddd/000000",
  },
  {
    id: 94,
    name: "Honey Ginger Tea",
    ref: "9WE5G06UW23",
    price: 2.99,
    rating: 4,
    desc: "Soothing tea with honey and ginger, great for relaxation.",
    image: "http://dummyimage.com/101x100.png/cc0000/ffffff",
  },
  {
    id: 95,
    name: "Stainless Steel Travel Mug",
    ref: "3YN9WN6PU50",
    price: 19.99,
    rating: 4,
    desc: "Insulated mug to keep drinks hot on the go.",
    image: "http://dummyimage.com/223x100.png/cc0000/ffffff",
  },
  {
    id: 96,
    name: "Organic Almonds",
    ref: "1T51G66TD02",
    price: 8.99,
    rating: 4,
    desc: "Crunchy and nutritious almonds, perfect for snacking.",
    image: "http://dummyimage.com/230x100.png/cc0000/ffffff",
  },
  {
    id: 97,
    name: "Compact Umbrella",
    ref: "8R14U68HD61",
    price: 12.99,
    rating: 5,
    desc: "Portable and lightweight umbrella for protection from rain.",
    image: "http://dummyimage.com/151x100.png/5fa2dd/ffffff",
  },
  {
    id: 98,
    name: "Denim Jacket",
    ref: "8AJ0KT9MP87",
    price: 69.99,
    rating: 1,
    desc: "A classic denim jacket that never goes out of style.",
    image: "http://dummyimage.com/101x100.png/cc0000/ffffff",
  },
  {
    id: 99,
    name: "Kids' STEM Robotics Kit",
    ref: "1TX9TH9HT50",
    price: 59.99,
    rating: 3,
    desc: "Educational robotics kit for building and programming.",
    image: "http://dummyimage.com/111x100.png/cc0000/ffffff",
  },
  {
    id: 100,
    name: "LED Christmas Lights",
    ref: "7M47VK3JN11",
    price: 29.99,
    rating: 2,
    desc: "Eco-friendly LED lights for festive decorations.",
    image: "http://dummyimage.com/211x100.png/cc0000/ffffff",
  },
];

export function getProducts () {
  return products;
};

export function getProductByRef (ref){
  const item = products.find(p => p.ref === ref)
  return item
}

