const products = [
  {
    id: 1,
    name: "Cranberry Almond Biscotti",
    price: 4.19,
    rating: 2,
    desc: "Crispy and delicious biscotti flavored with cranberry and almond.",
    image: "http://dummyimage.com/229x100.png/5fa2dd/ffffff",
  },
  {
    id: 2,
    name: "Kale Salad with Lemon Dressing",
    price: 4.99,
    rating: 2,
    desc: "Fresh kale salad with a zesty lemon dressing, great as a side dish.",
    image: "http://dummyimage.com/182x100.png/dddddd/000000",
  },
  {
    id: 3,
    name: "Ice Cream",
    price: 5.99,
    rating: 4,
    desc: "Rich and creamy ice cream, available in various flavors.",
    image: "http://dummyimage.com/170x100.png/5fa2dd/ffffff",
  },
  {
    id: 4,
    name: "Samoas Cookie Mix",
    price: 5.59,
    rating: 5,
    desc: "Baking mix to create your favorite Samoa-style cookies at home.",
    image: "http://dummyimage.com/103x100.png/cc0000/ffffff",
  },
  {
    id: 5,
    name: "Lemon Pepper Seasoning",
    price: 3.29,
    rating: 4,
    desc: "A zesty seasoning for meats and vegetables",
    image: "http://dummyimage.com/200x100.png/5fa2dd/ffffff",
  },
  {
    id: 6,
    name: "Mediterranean Couscous Salad",
    price: 5.49,
    rating: 1,
    desc: "Couscous salad with cucumbers, tomatoes, feta, and olives, ready to eat.",
    image: "http://dummyimage.com/105x100.png/5fa2dd/ffffff",
  },
  {
    id: 7,
    name: "Chocolate Covered Pretzels",
    price: 3.29,
    rating: 1,
    desc: "Crunchy pretzels coated in rich chocolate, a sweet treat.",
    image: "http://dummyimage.com/165x100.png/ff4444/ffffff",
  },
  {
    id: 8,
    name: "Silicone Ice Cube Tray",
    price: 10.99,
    rating: 4,
    desc: "Flexible tray for easy-release ice cubes.",
    image: "http://dummyimage.com/207x100.png/5fa2dd/ffffff",
  },
  {
    id: 9,
    name: "Art Supplies Organizer",
    price: 18.99,
    rating: 3,
    desc: "Storage organizer for art supplies and tools.",
    image: "http://dummyimage.com/173x100.png/ff4444/ffffff",
  },
  {
    id: 10,
    name: "Portable Solar Camp Shower",
    price: 29.99,
    rating: 2,
    desc: "Portable solar shower for camping and outdoor use.",
    image: "http://dummyimage.com/114x100.png/dddddd/000000",
  },
  {
    id: 11,
    name: "Silicone Cooking Utensils Set",
    price: 34.99,
    rating: 3,
    desc: "Non-stick and heat-resistant utensils for cooking.",
    image: "http://dummyimage.com/199x100.png/ff4444/ffffff",
  },
  {
    id: 12,
    name: "Tailored Dress Pants",
    price: 79.99,
    rating: 1,
    desc: "Smart tailored dress pants, perfect for work or formal events.",
    image: "http://dummyimage.com/195x100.png/cc0000/ffffff",
  },
  {
    id: 13,
    name: "Chocolate Dipped Fruit",
    price: 5.99,
    rating: 5,
    desc: "Fruits dipped in rich chocolate, perfect for desserts.",
    image: "http://dummyimage.com/174x100.png/ff4444/ffffff",
  },
  {
    id: 14,
    name: "Smartphone Gimbal Stabilizer",
    price: 89.99,
    rating: 1,
    desc: "Stabilizer for smooth video recording with smartphones.",
    image: "http://dummyimage.com/242x100.png/cc0000/ffffff",
  },
  {
    id: 15,
    name: "Chocolate Chip Energy Balls",
    price: 3.99,
    rating: 5,
    desc: "No-bake energy balls made with oats, chocolate chips, and honey.",
    image: "http://dummyimage.com/183x100.png/5fa2dd/ffffff",
  },
  {
    id: 16,
    name: "Basil Tomato Soup",
    price: 2.99,
    rating: 3,
    desc: "Rich tomato soup flavored with fresh basil, ready to heat up.",
    image: "http://dummyimage.com/124x100.png/cc0000/ffffff",
  },
  {
    id: 17,
    name: "Compact Hair Dryer",
    price: 29.99,
    rating: 4,
    desc: "Lightweight hair dryer with multiple speed settings.",
    image: "http://dummyimage.com/229x100.png/5fa2dd/ffffff",
  },
  {
    id: 18,
    name: "Customizable Wall Calendar",
    price: 24.99,
    rating: 4,
    desc: "Personalize your calendar with photos and special dates.",
    image: "http://dummyimage.com/162x100.png/dddddd/000000",
  },
  {
    id: 19,
    name: "Smoked Paprika",
    price: 2.99,
    rating: 3,
    desc: "Add a smoky flavor to your dishes.",
    image: "http://dummyimage.com/134x100.png/cc0000/ffffff",
  },
  {
    id: 20,
    name: "Pineapple Salsa",
    price: 4.29,
    rating: 5,
    desc: "Fresh salsa made with pineapple and spices",
    image: "http://dummyimage.com/242x100.png/ff4444/ffffff",
  },
  {
    id: 21,
    name: "Egg Noodles",
    price: 2.29,
    rating: 2,
    desc: "Wide egg noodles, perfect for casseroles and soups.",
    image: "http://dummyimage.com/135x100.png/ff4444/ffffff",
  },
  {
    id: 22,
    name: "Green Tea Matcha Powder",
    price: 15.99,
    rating: 1,
    desc: "High-quality matcha powder for smoothies and baking.",
    image: "http://dummyimage.com/150x100.png/cc0000/ffffff",
  },
  {
    id: 23,
    name: "Wireless Smart Plug",
    price: 19.99,
    rating: 1,
    desc: "Control home appliances remotely using your smartphone app.",
    image: "http://dummyimage.com/173x100.png/dddddd/000000",
  },
  {
    id: 24,
    name: "Pet Travel Bowl",
    price: 10.99,
    rating: 5,
    desc: "Collapsible travel bowl for pets on the go.",
    image: "http://dummyimage.com/211x100.png/cc0000/ffffff",
  },
  {
    id: 25,
    name: "Chipotle Lime Salsa",
    price: 3.99,
    rating: 3,
    desc: "Spicy salsa with chipotle and lime for a zesty kick.",
    image: "http://dummyimage.com/148x100.png/5fa2dd/ffffff",
  },
  {
    id: 26,
    name: "Samoas Cookie Mix",
    price: 5.59,
    rating: 2,
    desc: "Baking mix to create your favorite Samoa-style cookies at home.",
    image: "http://dummyimage.com/218x100.png/ff4444/ffffff",
  },
  {
    id: 27,
    name: "Spicy Tuna Sushi Kit",
    price: 8.99,
    rating: 2,
    desc: "Everything you need to make delicious spicy tuna rolls at home.",
    image: "http://dummyimage.com/155x100.png/ff4444/ffffff",
  },
  {
    id: 28,
    name: "Organic Coconut Yogurt",
    price: 4.49,
    rating: 5,
    desc: "Dairy-free yogurt made from coconut milk.",
    image: "http://dummyimage.com/190x100.png/cc0000/ffffff",
  },
  {
    id: 29,
    name: "Electric Kettle with Temperature Control",
    price: 49.99,
    rating: 5,
    desc: "Electric kettle that offers precise temperature settings.",
    image: "http://dummyimage.com/221x100.png/dddddd/000000",
  },
  {
    id: 30,
    name: "Greek Yogurt",
    price: 1.99,
    rating: 3,
    desc: "Creamy Greek yogurt packed with protein and probiotics.",
    image: "http://dummyimage.com/106x100.png/dddddd/000000",
  },
  {
    id: 31,
    name: "Chocolate Dipped Fruit",
    price: 5.99,
    rating: 5,
    desc: "Fruits dipped in rich chocolate, perfect for desserts.",
    image: "http://dummyimage.com/129x100.png/ff4444/ffffff",
  },
  {
    id: 32,
    name: "Tailored Dress Pants",
    price: 79.99,
    rating: 2,
    desc: "Smart tailored dress pants, perfect for work or formal events.",
    image: "http://dummyimage.com/102x100.png/5fa2dd/ffffff",
  },
  {
    id: 33,
    name: "Dried Apricots",
    price: 3.79,
    rating: 1,
    desc: "Sweet, chewy dried apricots, great for snacking or baking.",
    image: "http://dummyimage.com/191x100.png/ff4444/ffffff",
  },
  {
    id: 34,
    name: "Puzzle 3D Model Kit",
    price: 22.99,
    rating: 3,
    desc: "3D model puzzle kit for creative builders.",
    image: "http://dummyimage.com/207x100.png/ff4444/ffffff",
  },
  {
    id: 35,
    name: "Mango Sticky Rice Dessert",
    price: 4.5,
    rating: 3,
    desc: "Sweetened sticky rice served with fresh mango and coconut sauce.",
    image: "http://dummyimage.com/133x100.png/dddddd/000000",
  },
  {
    id: 36,
    name: "Veggie Lovers Pizza",
    price: 8.99,
    rating: 4,
    desc: "Frozen pizza loaded with fresh vegetables and mozzarella cheese.",
    image: "http://dummyimage.com/152x100.png/ff4444/ffffff",
  },
  {
    id: 37,
    name: "Elderberry Syrup Kit",
    price: 22.99,
    rating: 2,
    desc: "DIY kit to make your own elderberry syrup.",
    image: "http://dummyimage.com/130x100.png/dddddd/000000",
  },
  {
    id: 38,
    name: "Peanut Butter Pretzel Bites",
    price: 4.19,
    rating: 4,
    desc: "Crunchy pretzel bites filled with peanut butter",
    image: "http://dummyimage.com/113x100.png/cc0000/ffffff",
  },
  {
    id: 39,
    name: "Coffee Subscription Service",
    price: 29.99,
    rating: 3,
    desc: "Monthly subscription for freshly roasted coffee delivered to your door.",
    image: "http://dummyimage.com/228x100.png/ff4444/ffffff",
  },
  {
    id: 40,
    name: "Canned Coconut Milk",
    price: 1.89,
    rating: 2,
    desc: "Rich coconut milk, great for cooking and baking.",
    image: "http://dummyimage.com/242x100.png/cc0000/ffffff",
  },
  {
    id: 41,
    name: "Smartphone UV Sanitizer",
    price: 39.99,
    rating: 3,
    desc: "UV light sanitizer for phones and small items.",
    image: "http://dummyimage.com/212x100.png/5fa2dd/ffffff",
  },
  {
    id: 42,
    name: "LED Strip Light Kit",
    price: 39.99,
    rating: 2,
    desc: "Flexible light strips for creative home decor.",
    image: "http://dummyimage.com/106x100.png/ff4444/ffffff",
  },
  {
    id: 43,
    name: "Beef Stroganoff Meal Kit",
    price: 12.99,
    rating: 1,
    desc: "Complete meal kit with everything needed to make beef stroganoff in under 30 minutes.",
    image: "http://dummyimage.com/236x100.png/5fa2dd/ffffff",
  },
  {
    id: 44,
    name: "Coffee Making Kit",
    price: 44.99,
    rating: 2,
    desc: "Complete set to brew coffee with different methods.",
    image: "http://dummyimage.com/131x100.png/cc0000/ffffff",
  },
  {
    id: 45,
    name: "Kale & Quinoa Salad Mix",
    price: 4.49,
    rating: 1,
    desc: "A nutrient-packed salad mix with kale, quinoa, and a lemon vinaigrette, ready to eat.",
    image: "http://dummyimage.com/220x100.png/ff4444/ffffff",
  },
  {
    id: 46,
    name: "Elderberry Syrup Kit",
    price: 22.99,
    rating: 1,
    desc: "DIY kit to make your own elderberry syrup.",
    image: "http://dummyimage.com/215x100.png/ff4444/ffffff",
  },
  {
    id: 47,
    name: "Dark Chocolate Bars",
    price: 2.99,
    rating: 3,
    desc: "Rich dark chocolate bars, perfect for a sweet treat.",
    image: "http://dummyimage.com/187x100.png/dddddd/000000",
  },
  {
    id: 48,
    name: "Greek Yogurt",
    price: 1.99,
    rating: 1,
    desc: "Creamy Greek yogurt packed with protein and probiotics.",
    image: "http://dummyimage.com/157x100.png/5fa2dd/ffffff",
  },
  {
    id: 49,
    name: "Pet Hair Removal Brush",
    price: 14.99,
    rating: 2,
    desc: "Effective brush for removing loose hair from pets.",
    image: "http://dummyimage.com/179x100.png/cc0000/ffffff",
  },
  {
    id: 50,
    name: "DIY Candle Making Kit",
    price: 22.99,
    rating: 2,
    desc: "Everything you need to make your own candles.",
    image: "http://dummyimage.com/219x100.png/dddddd/000000",
  },
  {
    id: 51,
    name: "Mechanical Pencil Set",
    price: 19.99,
    rating: 4,
    desc: "Precision pencils for drawing, sketching, and writing.",
    image: "http://dummyimage.com/186x100.png/5fa2dd/ffffff",
  },
  {
    id: 52,
    name: "Thai Coconut Curry Sauce",
    price: 3.99,
    rating: 3,
    desc: "A rich coconut curry sauce perfect for simmering vegetables or meats.",
    image: "http://dummyimage.com/245x100.png/5fa2dd/ffffff",
  },
  {
    id: 53,
    name: "Portable Air Purifier",
    price: 69.99,
    rating: 5,
    desc: "Compact air purifier to improve indoor air quality.",
    image: "http://dummyimage.com/228x100.png/dddddd/000000",
  },
  {
    id: 54,
    name: "Frozen Chicken Nuggets",
    price: 4.49,
    rating: 1,
    desc: "Crispy chicken nuggets for quick meals.",
    image: "http://dummyimage.com/113x100.png/5fa2dd/ffffff",
  },
  {
    id: 55,
    name: "Apple Cinnamon Oatmeal",
    price: 2.89,
    rating: 3,
    desc: "Warm oatmeal flavored with apple and cinnamon.",
    image: "http://dummyimage.com/106x100.png/cc0000/ffffff",
  },
  {
    id: 56,
    name: "Pumpkin Spice Cookies",
    price: 3.29,
    rating: 4,
    desc: "Delicious cookies flavored with pumpkin and spices.",
    image: "http://dummyimage.com/164x100.png/ff4444/ffffff",
  },
  {
    id: 57,
    name: "Bamboo Bathtub Caddy",
    price: 34.99,
    rating: 3,
    desc: "Expandable caddy for holding books, phones, and snacks while in the bath.",
    image: "http://dummyimage.com/242x100.png/dddddd/000000",
  },
  {
    id: 58,
    name: "Sea Salt Tortilla Chips",
    price: 2.49,
    rating: 2,
    desc: "Crunchy tortilla chips with a hint of sea salt, great with dips.",
    image: "http://dummyimage.com/236x100.png/5fa2dd/ffffff",
  },
  {
    id: 59,
    name: "Chickpea Pasta",
    price: 4.19,
    rating: 4,
    desc: "Healthy pasta alternative made from chickpeas",
    image: "http://dummyimage.com/163x100.png/ff4444/ffffff",
  },
  {
    id: 60,
    name: "Ergonomic Mouse Pad with Wrist Support",
    price: 14.99,
    rating: 1,
    desc: "Comfortable mouse pad designed to reduce wrist strain.",
    image: "http://dummyimage.com/201x100.png/cc0000/ffffff",
  },
  {
    id: 61,
    name: "Sushi Rice",
    price: 3.99,
    rating: 2,
    desc: "Short-grain sushi rice for perfect rolls.",
    image: "http://dummyimage.com/193x100.png/5fa2dd/ffffff",
  },
  {
    id: 62,
    name: "Almond Flour Biscuits",
    price: 6.49,
    rating: 5,
    desc: "Gluten-free biscuits made with almond flour.",
    image: "http://dummyimage.com/238x100.png/dddddd/000000",
  },
  {
    id: 63,
    name: "Tattoo Kit",
    price: 99.99,
    rating: 4,
    desc: "Complete tattoo kit for beginners and professionals.",
    image: "http://dummyimage.com/135x100.png/5fa2dd/ffffff",
  },
  {
    id: 64,
    name: "Classic Bagels",
    price: 2.99,
    rating: 4,
    desc: "Freshly baked bagels, perfect for breakfast or snacks.",
    image: "http://dummyimage.com/196x100.png/cc0000/ffffff",
  },
  {
    id: 65,
    name: "Wireless HDMI Receiver",
    price: 49.99,
    rating: 1,
    desc: "Stream HD video wirelessly from devices to TV.",
    image: "http://dummyimage.com/138x100.png/ff4444/ffffff",
  },
  {
    id: 66,
    name: "Blue Corn Tortilla Chips",
    price: 3.49,
    rating: 2,
    desc: "Crunchy chips made from blue corn, perfect for dipping.",
    image: "http://dummyimage.com/112x100.png/ff4444/ffffff",
  },
  {
    id: 67,
    name: "Herbed Chicken Breast",
    price: 7.99,
    rating: 3,
    desc: "Marinated chicken breast seasoned with herbs, ready for grilling.",
    image: "http://dummyimage.com/249x100.png/dddddd/000000",
  },
  {
    id: 68,
    name: "Reusable Produce Bags Set",
    price: 14.99,
    rating: 5,
    desc: "Eco-friendly mesh bags for shopping produce at the market.",
    image: "http://dummyimage.com/198x100.png/5fa2dd/ffffff",
  },
  {
    id: 69,
    name: "Vanilla Almond Granola",
    price: 4.29,
    rating: 3,
    desc: "Crunchy granola with almonds and a hint of vanilla, perfect for breakfast.",
    image: "http://dummyimage.com/216x100.png/cc0000/ffffff",
  },
  {
    id: 70,
    name: "Black Bean Salsa",
    price: 3.49,
    rating: 5,
    desc: "Spicy salsa made with black beans and tomatoes.",
    image: "http://dummyimage.com/248x100.png/5fa2dd/ffffff",
  },
  {
    id: 71,
    name: "Electronic Drum Kit",
    price: 359.99,
    rating: 4,
    desc: "Compact electronic drum kit for musicians of all levels.",
    image: "http://dummyimage.com/219x100.png/5fa2dd/ffffff",
  },
  {
    id: 72,
    name: "LED Table Lamp",
    price: 29.99,
    rating: 1,
    desc: "Modern LED table lamp with touch control.",
    image: "http://dummyimage.com/161x100.png/dddddd/000000",
  },
  {
    id: 73,
    name: "Linen Trousers",
    price: 44.99,
    rating: 5,
    desc: "Breathable linen trousers perfect for hot weather.",
    image: "http://dummyimage.com/213x100.png/5fa2dd/ffffff",
  },
  {
    id: 74,
    name: "Travel Luggage Scale",
    price: 14.99,
    rating: 5,
    desc: "Digital scale to avoid overweight baggage fees.",
    image: "http://dummyimage.com/237x100.png/cc0000/ffffff",
  },
  {
    id: 75,
    name: "Pet Carrier Backpack",
    price: 39.99,
    rating: 2,
    desc: "Comfortable and breathable backpack for carrying small pets.",
    image: "http://dummyimage.com/112x100.png/5fa2dd/ffffff",
  },
  {
    id: 76,
    name: "Traditional Hummus",
    price: 3.29,
    rating: 2,
    desc: "Creamy chickpea dip blended with tahini and garlic.",
    image: "http://dummyimage.com/241x100.png/5fa2dd/ffffff",
  },
  {
    id: 77,
    name: "Portable Water Filter",
    price: 29.99,
    rating: 4,
    desc: "Lightweight water filter for outdoor adventures.",
    image: "http://dummyimage.com/193x100.png/5fa2dd/ffffff",
  },
  {
    id: 78,
    name: "Chicken Breasts",
    price: 9.99,
    rating: 2,
    desc: "Juicy and tender boneless chicken breasts.",
    image: "http://dummyimage.com/106x100.png/ff4444/ffffff",
  },
  {
    id: 79,
    name: "Chocolate Avocado Pudding",
    price: 4.99,
    rating: 1,
    desc: "Rich and creamy pudding made with ripe avocados and cocoa.",
    image: "http://dummyimage.com/214x100.png/cc0000/ffffff",
  },
  {
    id: 80,
    name: "Honey BBQ Riblets",
    price: 12.99,
    rating: 2,
    desc: "Tender riblets coated in a honey barbecue glaze, perfect for grilling or baking.",
    image: "http://dummyimage.com/248x100.png/dddddd/000000",
  },
  {
    id: 81,
    name: "Tomato Paste",
    price: 1.29,
    rating: 2,
    desc: "Concentrated tomato paste, great for sauces.",
    image: "http://dummyimage.com/229x100.png/cc0000/ffffff",
  },
  {
    id: 82,
    name: "Backpacking Tent",
    price: 109.99,
    rating: 2,
    desc: "Lightweight and durable tent for camping trips.",
    image: "http://dummyimage.com/100x100.png/ff4444/ffffff",
  },
  {
    id: 83,
    name: "Grilled Veggie Burgers",
    price: 6.29,
    rating: 4,
    desc: "Delicious veggie burgers loaded with grilled vegetables.",
    image: "http://dummyimage.com/112x100.png/ff4444/ffffff",
  },
  {
    id: 84,
    name: "Herbal Garden Starter Kit",
    price: 24.99,
    rating: 1,
    desc: "Indoor gardening kit with herbs and pots.",
    image: "http://dummyimage.com/124x100.png/cc0000/ffffff",
  },
  {
    id: 85,
    name: "Multicolored LED Strip Lights",
    price: 29.99,
    rating: 1,
    desc: "Flexible LED lights for creative home lighting designs.",
    image: "http://dummyimage.com/182x100.png/dddddd/000000",
  },
  {
    id: 86,
    name: "Coconut Chia Pudding",
    price: 3.49,
    rating: 3,
    desc: "Creamy chia pudding made with coconut milk and topped with mango.",
    image: "http://dummyimage.com/140x100.png/5fa2dd/ffffff",
  },
  {
    id: 87,
    name: "Lentil Vegetable Stew",
    price: 4.49,
    rating: 3,
    desc: "Hearty stew made with lentils and mixed vegetables, vegan-friendly.",
    image: "http://dummyimage.com/174x100.png/dddddd/000000",
  },
  {
    id: 88,
    name: "Magnetic Phone Case",
    price: 19.99,
    rating: 4,
    desc: "Stylish case with magnetic closure for smartphones.",
    image: "http://dummyimage.com/143x100.png/cc0000/ffffff",
  },
  {
    id: 89,
    name: "Pesto Genovese",
    price: 6.49,
    rating: 1,
    desc: "Traditional basil pesto made with extra virgin olive oil.",
    image: "http://dummyimage.com/172x100.png/ff4444/ffffff",
  },
  {
    id: 90,
    name: "Silicone Baking Mat Set",
    price: 24.99,
    rating: 1,
    desc: "Non-stick and reusable mats for easy baking.",
    image: "http://dummyimage.com/160x100.png/ff4444/ffffff",
  },
  {
    id: 91,
    name: "Veggie Burger Patties",
    price: 5.99,
    rating: 5,
    desc: "Delicious veggie burger patties for grilling or frying.",
    image: "http://dummyimage.com/113x100.png/dddddd/000000",
  },
  {
    id: 92,
    name: "Green Smoothie Mix",
    price: 5.99,
    rating: 2,
    desc: "A convenient powder mix combining greens and fruits for smoothies.",
    image: "http://dummyimage.com/149x100.png/dddddd/000000",
  },
  {
    id: 93,
    name: "Elegant Lace Dress",
    price: 79.99,
    rating: 3,
    desc: "A stunning lace dress perfect for special occasions.",
    image: "http://dummyimage.com/196x100.png/5fa2dd/ffffff",
  },
  {
    id: 94,
    name: "Chickpea Flour",
    price: 3.29,
    rating: 4,
    desc: "Gluten-free flour made from ground chickpeas, great for cooking.",
    image: "http://dummyimage.com/221x100.png/dddddd/000000",
  },
  {
    id: 95,
    name: "Fashionable Fanny Pack",
    price: 24.99,
    rating: 2,
    desc: "A trendy fanny pack, perfect for hands-free outings.",
    image: "http://dummyimage.com/242x100.png/5fa2dd/ffffff",
  },
  {
    id: 96,
    name: "Hand Crank Blender",
    price: 18.99,
    rating: 5,
    desc: "Manual blender for smoothies and mixing ingredients on the go.",
    image: "http://dummyimage.com/173x100.png/dddddd/000000",
  },
  {
    id: 97,
    name: "Lentil Soup",
    price: 2.49,
    rating: 3,
    desc: "Flavorful lentil soup, perfect for a quick meal.",
    image: "http://dummyimage.com/200x100.png/ff4444/ffffff",
  },
  {
    id: 98,
    name: "Educational STEM Kit",
    price: 35.99,
    rating: 3,
    desc: "Hands-on experience with science and engineering projects.",
    image: "http://dummyimage.com/110x100.png/ff4444/ffffff",
  },
  {
    id: 99,
    name: "Cranberry Orange Juice",
    price: 2.49,
    rating: 3,
    desc: "Refreshing juice blend of cranberries and oranges.",
    image: "http://dummyimage.com/102x100.png/5fa2dd/ffffff",
  },
  {
    id: 100,
    name: "Vegetarian Chili",
    price: 3.99,
    rating: 2,
    desc: "Hearty chili made with beans and vegetables, a savory meal option.",
    image: "http://dummyimage.com/172x100.png/5fa2dd/ffffff",
  },
];

const getProducts = () => {
  return products;
}

export default getProducts